### ISSUE TITLE
Project doesn't build on Arduino 1.8

### ISSUE THREAD

**Issue by killercode** [jeffmer/tinyPulsePPG#4]
Hello

Downloaded the source code and the first issue I found is that there are 2 filenames with the same name, difference is on capitalized letters and windows doesn't accept it.

After that opening the project will give errors like: 

'USISR' was not declared in this scope

**Comment by jeffmer** [comment]
Don’t know how that happened. I have deleted the duplicate file. The error that you have is usually caused by having the wrong target selected.

**Comment by karimelc** [comment]
Hi @killercode, I'm having the same issue as you (USISR etc.), did you find a solution yet?

**Comment by jeffmer** [comment]
Is this an issue with the Attiny85 or the Nano version? My advice would be to see if you can build the nano version which uses fairly standard Arduino libraries.

**Comment by karimelc** [comment]
Hi @jeffmer, you are correct, the nano version builds fine after reinstall/cleaning. Thanks!

**Comment by killercode** [comment]
Yes, I solved it:
1- Installed the library attinycore
2- removed the duplicate file
3- renamed the folder to match the .ino file name

Also I added an ifndef on the MAX30102.h file

I will post a fix for this now

**Comment by killercode** [comment]
Hello, here is a fix for the problems I found

Pull Request: #5 

Hope it helps
